# Your info

Full name: mohammad yarmoghadam

Student ID: 96462104

# Q1. Hopfield

## Q1.2

In [15]:
# Q1.2_graded
# Do not change the above line.

# This cell is for your imports.

import numpy as np
import matplotlib.pyplot as plt

In [16]:
# Q1.2_graded
# Do not change the above line.

# This cell is for your codes.

templates = [[1, -1, 1, -1, 1, -1], [1, 1, 1, -1, -1, -1]]

weights = np.ndarray((6, 6), buffer=np.full(6*6, 0), dtype=float)
for item in templates: 
  for i in range(6):
    for j in range(i):
      weights[i, j] += item[i] * item[j]
      weights[j, i] = weights[i, j] 
      

np.fill_diagonal(weights, 0)
print(weights)
print(np.sign(np.dot(templates[0], weights)))
print(np.sign(np.dot(templates[1], weights)))
energy_of_network = np.ndarray((len(templates), 1), 
                               buffer=np.full(len(templates), 0), dtype=float)

for ind, item in enumerate(templates):
  for i in range(6):
    for j in range(6):
      energy_of_network[ind] = weights[i][j] * item[i] * item[j]
energy_of_network /= 2

print(energy_of_network)

[[ 0.  0.  2. -2.  0. -2.]
 [ 0.  0.  0.  0. -2.  0.]
 [ 2.  0.  0. -2.  0. -2.]
 [-2.  0. -2.  0.  0.  2.]
 [ 0. -2.  0.  0.  0.  0.]
 [-2.  0. -2.  2.  0.  0.]]
[ 1. -1.  1. -1.  1. -1.]
[ 1.  1.  1. -1. -1. -1.]
[[0.]
 [0.]]


## Q1.3

In [17]:
# Q1.3_graded
# Do not change the above line.

# This cell is for your imports.

!wget "https://www.cufonfonts.com/download/rf/arial"
!pwd
!mkdir -p dataset
!mv arial dataset/
!cd dataset
!unzip dataset/arial -d dataset/
!mv dataset/ARIAL.TTF /usr/share/fonts/truetype/
!cd ..
!rm -rf dataset/

--2021-06-06 19:36:11--  https://www.cufonfonts.com/download/rf/arial
Resolving www.cufonfonts.com (www.cufonfonts.com)... 104.26.8.47, 172.67.73.52, 104.26.9.47, ...
Connecting to www.cufonfonts.com (www.cufonfonts.com)|104.26.8.47|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.cufonfonts.com/download/font/arial [following]
--2021-06-06 19:36:12--  https://www.cufonfonts.com/download/font/arial
Reusing existing connection to www.cufonfonts.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 3834335 (3.7M) [application/zip]
Saving to: ‘arial’

arial               100%[===================>]   3.66M  --.-KB/s    in 0.06s   

2021-06-06 19:36:12 (66.1 MB/s) - ‘arial’ saved [3834335/3834335]

/content
Archive:  dataset/arial
  inflating: dataset/ARIAL.TTF       
  inflating: dataset/ARIALN.TTF      
  inflating: dataset/ARIALI 1.TTF    
  inflating: dataset/ARIALI.TTF      
  inflating: dataset/ARIALNI.TTF     
  inflating: dataset/Ar

In [18]:
# Q1.3_graded
# Do not change the above line.

# This cell is for your codes.
import os         
import numpy as np
from PIL import Image, ImageFont
import matplotlib.pyplot as plt


def calculate_accuracy(patterns, noise_templates, weights):
  sum = 0
  for index, item in enumerate(noise_templates):
    sign_im = np.sign(np.dot(item, weights))
    sum += np.sum(sign_im == patterns[index]) / patterns[index].shape[0]
  return sum / len(noise_templates)


def noise_template(templates, noise):
  max_pixel = templates[0].shape
  count_noise = int(max_pixel[0] * noise)
  result = []
  for index, template in enumerate(templates):
    for i in np.random.randint(max_pixel[0], size=count_noise):
      templates[index][i] = template[i] * -1
    result.append(template)
  return result


def calculate_weights(templates, lenght):
  weights = np.ndarray(lenght,
                       buffer=np.full(lenght[0] * lenght[1], 0), dtype=float)
  for item in templates: 
    for i in range(lenght[0]):
      for j in range(i):
        weights[i, j] += item[i] * item[j]
        weights[j, i] = weights[i, j] 
  return weights


def create_templates(size):
  font = ImageFont.truetype("/usr/share/fonts/truetype/ARIAL.TTF", size)
  max_pixel = (-1,)
  templates = []
  for item in "ABCDEFGHIJ":
    attribute = font.getmask(item)
    temp_image = Image.Image()._new(attribute)
    data_of_img = temp_image.getdata()
    pixels_of_img = np.array(data_of_img)
    if pixels_of_img.shape[0] > max_pixel[0]:
      max_pixel = pixels_of_img.shape
    templates.append(pixels_of_img)
  final_templates = []
  for item in templates:
    item_size = len(item)
    if item_size == max_pixel[0]:
      continue
    size_of_shift = max_pixel[0] - item_size
    final_template = np.zeros(max_pixel)
    final_template[int(size_of_shift/2):int(len(item) + size_of_shift/2)] = item
    final_template = np.where(final_template > 0, 1, final_template)
    final_templates.append(np.where(final_template == 0, -1, final_template))
  return final_templates

noise1 = 0.1
noise2 = 0.3
noise3 = 0.6


first_font = create_templates(16)
second_font = create_templates(32)
third_font = create_templates(64)


first_weights = calculate_weights(first_font, (first_font[0].shape[0],
                                                 first_font[0].shape[0]))
second_weights = calculate_weights(second_font, (second_font[0].shape[0],
                                                  second_font[0].shape[0]))
third_weights = calculate_weights(third_font, (third_font[0].shape[0],
                                                 third_font[0].shape[0]))


print("first noise = " + str(noise1))
print(calculate_accuracy(third_font,
                         noise_template(third_font, noise1),
                         third_weights))
print(calculate_accuracy(second_font,
                         noise_template(second_font, noise1),
                         second_weights))
print(calculate_accuracy(first_font,
                         convert_to_noisy_pattern(first_font, noise1),
                         first_weights))

print("second noise = " + str(noise2))
print(calculate_accuracy(third_font,
                         noise_template(third_font, noise2),
                         third_weights))
print(calculate_accuracy(second_font,
                         noise_template(second_font, noise2),
                         second_weights))
print(calculate_accuracy(first_font,
                         noise_template(first_font, noise2),
                         first_weights))

print("third noise = " + str(noise3))
print(calculate_accuracy(third_font,
                         noise_template(third_font, noise3), 
                         third_weights))
print(calculate_accuracy(second_font,
                         noise_template(second_font, noise3),
                         second_weights))
print(calculate_accuracy(first_font,
                         noise_template(first_font, noise3),
                         first_weights))


first noise = 0.1
0.8501388888888889
0.8767149758454107
0.8717948717948717
second noise = 0.3
0.6940277777777778
0.7080193236714977
0.6994301994301996
third noise = 0.6
0.5589814814814815
0.5472463768115943
0.547008547008547


# <font color='red'>Submission</font>

1. Sign up in [Gradescope](https://www.gradescope.com) with proper name and student ID and use the following code to join the class: <font color='green'>**D5372R**</font>
2. Fill in your full name (seperated by single spaces) and student ID in the beginning of this notebook.
3. After you're done with this notebook, you should do the following:
  - Clear all outputs of the notebook.
  ![clear all outputs](https://i.ibb.co/y6FrttB/Screen-Shot-2021-03-21-at-01-51-42.png)
  - Run all of the cells (if you skipped a question just leave the cell unchanged), and make sure all of your outputs are correct.
  ![run all](https://i.ibb.co/cgRcBZ0/Screen-Shot-2021-03-21-at-01-54-58.png)
  - Save your notebook.
  - If you're using Colab, download your notebook.
  ![download ipynb](https://i.ibb.co/2KxYM6K/Screen-Shot-2021-03-21-at-02-03-50.png)
  - Put the notebook file you just downloaded and `convert.py` in the same folder run the following command:
  ```bash
  python convert.py
  ```
  This will export your code for each question into a `.py` file.
    - **Note**: if you want to add more cells, add this to the **first** line of the cell:
  ```python
  # Q5_graded
  ```
  according to the question number.
  - There are 2 assignments in Gradescope:

    ![assignments](https://i.ibb.co/10GMhGM/Screen-Shot-2021-03-21-at-02-16-25.png)
  
    You should upload your **codes** and your **notebook** in `HW3` section and your final report for all of the questions as a **single pdf** file in `HW3 - Report`. Autograder will automatically check for:
    - `CI992_HW3.ipynb`
    - `Q1.2.py`
    - `Q1.3.py`
    - `inverted_pendulum.fcl`
    - Your name and ID in the beginning of `.ipynb` file.

    It is important that you <font color='red'>**don't**</font> change the names of these files before submission.

4. If you pass the autograder, you're good to go.